#1151 Changed enum constants to keep contiguous array and modifies index/search strategy
* Changed enum constant tracking to keep contiguous array

* Enum constants array now allocates space necessary for reflection data instead of constant max size. Moved enum reflection functions to new struct for reuse.

* Fixed/modified tests for Enum reflection. Handled some edge cases.

* Default enum constants array to 1 in the case that no constants are found.

* Fixed possible out of bounds issue in sanitize build by using explicit ternary instead of short-circuiting or-operator

* Fixed error with signed->unsigned conversion with --strict

* Add support for Enum bitmasks up to max storage cap. Added support for nearly unbounded enum template recursion to bypass default search upper bound of 900. Added support for varied underlying enum types.

* Finished enum implementation. Added tests

* Fixed --strict type conversion complaints

* Fixed clang compilation difference -- fixed issue with clang enum-constant validation not detecting negative numbers as invalid constants.

* Fixes MVSC Error C2977 -- Lacks support for variadic templates. Instead use optional template parameter that defaults to void*=nullptr to supply arguments.

* Attempting to fix issue that could be caused by negative enum mask in MVSC.

* Readded negative bitmask support. Removed variadic templates/template null-default and trying parameterless-variant to solve MSVC build issues.

* Moved enum reflection init code out of enum_type to try and circumvent odd MSVC compiler issues.

* * Added test for enum with contiguous+sparse bitmask sections.

* Added comments to enum reflection code.

* Added fallback on enum-constant lookup to component relationship if
  reflection lookup fails.

* Swapped enum constant lookup fallback from relationship-lookup to filter-find